### ISSUE TITLE
bash: nvm: command not found

### ISSUE THREAD

**Issue by mmmpop** [devilbox/docker-php-fpm#119]
Looks like this newest commit is causing an issue when starting a session:
```bash
bash: nvm: command not found
```

When you run ```nvm``` in the shell it seems to be there though.

**Comment by cytopia** [comment]
> Looks like this newest commit is causing an issue when starting a session:
> 
> ```shell
> bash: nvm: command not found
> ```

@mmmpop can you explain what you mean "session"

**Comment by cytopia** [comment]
@mmmpop `nvm` is not a command itself, it is a bash function by the same name set in your environment:

```bash
$ set | grep -EA 7 '^nvm\s*\('

nvm ()
{
    if [ $# -lt 1 ]; then
        nvm --help;
        return;
    fi;
    local DEFAULT_IFS;
    DEFAULT_IFS=" $(nvm_echo t | command tr t \\t)
...
```

So this will only work if your bash config is sourced. So I would classify this as normal behaviour if you don't have different use cases otherwise.

If that causes any issues, please let me know and I will re-open this one.
