### ISSUE TITLE
Disable Extension does not seem to work: PHP_MODULES_DISABLE

### ISSUE THREAD

**Issue by dominikzogg** [devilbox/docker-php-fpm#148]
https://devilbox.readthedocs.io/en/latest/intermediate/enable-disable-php-modules.html#disable-php-modules

```sh
devilbox@php-7.3.12 in /shared/httpd $ echo $PHP_MODULES_DISABLE
dba,enchant,gmp,igbinary,imap,interbase,ldap,mcrypt,memcached,msgpack,OAuth,oci8,pdo_dblib,PDO_Firebird,PDO_OCI,pdo_pgsql,pdo_sqlsrv,pgsql,phalcon,pspell,rdkafka,recode,redis,snmp,sqlsrv,swoole,tidy,uploadprogress,xmlrpc
```
It seems the environment variable gets ignored

**Comment by dominikzogg** [comment]
The env variable seems to be: DISABLE_MODULES, do i use the wrong documentation?

**Comment by cytopia** [comment]
The env var for the PHP container is `DISABLE_MODULES` as described here: https://github.com/devilbox/docker-php-fpm#environment-variables

When this is being used for the Devilbox, it is prefixed with `PHP_` in order to group variables for its `.env` file: https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L133

**Comment by dominikzogg** [comment]
@cytopia thx
