### ISSUE TITLE
Docker manifest error 

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#186]
Hello @cytopia 
This is not the first one that occured. 

When we try to get new docker php-fpm images, we got such issue 

```
ERROR: for php  manifest for devilbox/php-fpm:7.3-work-0.120 not found: manifest unknown: manifest unknown
ERROR: manifest for devilbox/php-fpm:7.3-work-0.120 not found: manifest unknown: manifest unknown
```

Reason is tag missing; see at docker hub : 

![hub_docker_com_r_devilbox_php-fpm_tags](https://user-images.githubusercontent.com/364342/101235901-cc13a580-36cc-11eb-920a-784af476e2cd.png)

**Comment by cytopia** [comment]
Reason is: I'm having way too many CI jobs and Travis is not keeping up. One of my .org is even out of credits since weeks.
It simply has not yet built :-(

* https://travis-ci.org/github/devilbox/docker-php-fpm/branches
* https://travis-ci.org/github/devilbox/docker-php-fpm/builds/747674118

I am already slowly preparing the switch to GitHub Actions, it is however pretty time-consuming as it lacks some functionality Travis offers.

**Comment by llaville** [comment]
Understood. Thanks for quick answer !

**Comment by cytopia** [comment]
This repo is already pretty much prepared to be switched. There is however still a case sometimes when GitHub Actions succeed sand Travis fails (which is definitely an error). Once I've figured this out, I will have GitHub Actions do the push to Dockerhub and disable Travis here.

**Comment by cytopia** [comment]
Will close this.
