### ISSUE TITLE
Add please support for zsh and Oh My Zsh

### ISSUE THREAD

**Issue by andrewskigar** [devilbox/docker-php-fpm#36]

**Comment by cytopia** [comment]
@andrewskigar 
Next Release will have ZSH bundled

**Comment by cytopia** [comment]
@andrewskigar zsh is bundled.

**Comment by Luc45** [comment]
How can I enable it instead of bash?

**Comment by cytopia** [comment]
@Luc45 
Just type `zsh` inside the container and you should get the shell

**Comment by science695** [comment]
You can also change/duplicate the shell.sh or shell.bat and replace bash with zsh.

**Comment by alemicro** [comment]
Hi, how can I use the configurazione that I put in ./bash/bashrc.sh with zsh shell ?

**Comment by LedzZm** [comment]
@alemicro, as @science695 mentioned, you can change the shell.sh to use this line instead of it's default `docker-compose exec --user devilbox php zsh -l`. 
Alternatively you can create your own file (zsh.sh for example) and use this instead of shell.sh to enter your container's shell.

@cytopia Following up on the question of @alemicro , is it possible to initiate the containers with oh-my-zsh (and other plugins like zsh-autosuggestions and fzf) already installed?

Lastly I unsuccessfully tried to create a zsh folder with preset .zshrc and .zshenv files (like bash works). How could someone use predefined aliases and functions when using zsh?
